FROM mcr.microsoft.com/dotnet/sdk:9.0 AS base
COPY . /home
RUN dotnet restore /home/master-workshop-api.csproj
RUN dotnet publish /home/master-workshop-api.csproj -o publish

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app
COPY --from=base /publish /app/

EXPOSE 5002
ENV ASPNETCORE_URLS=http://+:5002
CMD [ "dotnet", "master-workshop-api.dll" ]