FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20
COPY --from=build /app/dist/master-workshop-frontend/ /usr/share/app
EXPOSE 4000

CMD ["node", "/usr/share/app/server/server.mjs"]